#!/usr/bin/env ruby

require 'prompt'

extend Prompt::DSL

@pwd = File.absolute_path Dir.pwd

dynamic_variable :dir, "Directory" do
  Dir.entries(@pwd).select do |e|
    File.directory?(File.join(@pwd, e))
  end
end

command "cd :dir", "Change directory" do |dir|
  @pwd = File.absolute_path File.join(@pwd, dir)
end

command "ls", "List files" do
  puts @pwd
  Dir.entries(@pwd).select do |e|
    path = File.join(@pwd, e)
    if File.directory?(path)
      puts "#{e}/"
    else
      puts e
    end
  end
end

command "pwd", "Print current directory" do
  puts @pwd
end

Prompt::Console.start
