#!/usr/bin/env ruby

require 'prompt'

extend Prompt::DSL

def change_prompt dir
  Prompt.application.prompt = "#{@pwd}> "
end

@pwd = File.expand_path Dir.pwd
change_prompt @pwd

param :dir, "Directory" do
  Dir.entries(@pwd).select do |e|
    File.directory?(File.join(@pwd, e))
  end
end

command "cd :dir", "Change directory" do |dir|
  @pwd = File.expand_path File.join(@pwd, dir)
  change_prompt @pwd
end

command "ls", "List files" do
  puts @pwd
  Dir.entries(@pwd).select do |e|
    path = File.join(@pwd, e)
    if File.directory?(path)
      puts "#{e}/"
    else
      puts e
    end
  end
end

command "pwd", "Print current directory" do
  puts @pwd
end

param :file, "File" do
  Dir.entries(@pwd).select do |e|
    File.file?(File.join(@pwd, e))
  end
end

command "cp *file :dir", "Copy one or more files to dest" do |files, dir|
  puts "Copying #{files.length} file(s) to #{dir}"
  # doesn't actually do it...
end

Prompt::Console.start
