#!/usr/bin/env ruby

require 'prompt'

extend Prompt::DSL

GRUE = 3
@moves = 0

group "Move"

param :direction, "A cardinal direction", %w(north east south west)

desc "Walk in the specified direction"
command "go :direction" do |direction|
  puts "You walked #{direction}"
  @moves += 1
  if @moves > GRUE
  	puts "You have been eaten by a grue"
  	exit
  end
end

group "Interact"

desc "Look around"
command "look" do
  if @moves < GRUE
  	puts "You're in a nice, well-lit room"
  else
  	puts "It is pitch black. You are likely to be eaten by a grue."
  end
end

desc "Say something"
command "say *something" do |something|
  puts "You say '#{something.join(" ")}'"
end

Prompt::Console.start
